# This is Foreman's configuration file. You can edit it to tell Foreman about
# new tools that you'd like to install, or to change versions of tools you
# already have.

# When adding new tools, make sure to run `foreman install` so that their
# binaries are installed.

# Put any tools you want to install here. To install Rojo 7, you'd use:

[tools]
wally = { source = "UpliftGames/wally", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "x" }
selene = {source = "Kampfkarren/selene", version = "x"}
moonwave = {source = "evaera/moonwave", version = "x"}